<?php
/**
 * Magento
 *
 */
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
  <?php echo $this->getChildHtml('global_notices') ?>
  <div class="page">
    <?php echo $this->getChildHtml('header') ?>
    <div class="main-container col1-layout">
      <div class="main">
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="col-main">
          <?php echo $this->getChildHtml('global_messages') ?>
          <div class="slideshow">
            <?php echo $this->getChildHtml('content') ?>
          </div> 
          <ul class="callouts inline">
            <li><a href="#"><img src="<?php echo $this->getSkinUrl(); ?>/images/mens-cat.png" alt="Men's Wear" /></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl(); ?>/images/womens-cat.png" alt="Women's Wear" /></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl(); ?>/images/sales-rep-link.png" alt="Become a Sales Rep" /></a></li>
            <li class="last-callout"><a href="#"><img src="<?php echo $this->getSkinUrl(); ?>/images/promo-link.png" alt="Battle of the Bugs" /></a></li>
          </ul>
        </div>
      </div>
    </div>
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
  </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
<script src="/js/jquery/cycle.js" type="text/javascript"></script>
<script>
jQuery(function($){
  $('.feature').cycle({
    fx: 'fade',
    timeout: 6000,
    speed: 600,
    pager: '#pager'
  });
});
</script>
</body>
</html>
